# Generated by Django 3.1.3 on 2020-11-29 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('legislature', models.TextField()),
                ('titreDossiertitre', models.TextField()),
                ('titreDossier_titreChemin', models.TextField()),
                ('titreDossier_senatChemin', models.TextField()),
                ('procedureParlementaire_code', models.TextField()),
                ('procedureParlementaire_libelle', models.TextField()),
                ('fusionDossier', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActeLegislatif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('codeActe', models.TextField()),
                ('libelleActeNomCanonique', models.TextField()),
                ('libelleActeLibelleCourt', models.TextField()),
                ('organeRef', models.TextField()),
                ('dateActe', models.TextField(null=True)),
                ('texteAssocie', models.TextField(null=True)),
                ('provenance', models.TextField(null=True)),
                ('reunion', models.TextField(null=True)),
                ('texteLoiRef', models.TextField(null=True)),
                ('infoJO_typeJO', models.TextField(null=True)),
                ('infoJO_dateJO', models.TextField(null=True)),
                ('infoJO_pageJO', models.TextField(null=True)),
                ('infoJO_numJO', models.TextField(null=True)),
                ('infoJO_urlLegifrance', models.TextField(null=True)),
                ('infoJO_referenceNOR', models.TextField(null=True)),
                ('urlEcheancierLoi', models.TextField(null=True)),
                ('codeLoi', models.TextField(null=True)),
                ('titreLoi', models.TextField(null=True)),
                ('acteLegislatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actelegislatif')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dossier')),
            ],
        ),
    ]
