# Generated by Django 3.1.3 on 2020-11-29 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossier',
            old_name='titreDossiertitre',
            new_name='titreDossier_titre',
        ),
    ]
