# Generated by Django 3.1.3 on 2020-11-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201129_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='titreDossier_senatChemin',
            field=models.TextField(null=True),
        ),
    ]
