# Generated by Django 3.1.3 on 2020-11-29 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201129_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actelegislatif',
            old_name='libelleActeLibelleCourt',
            new_name='libelleActe_libelleCourt',
        ),
        migrations.RenameField(
            model_name='actelegislatif',
            old_name='libelleActeNomCanonique',
            new_name='libelleActe_nomCanonique',
        ),
        migrations.AlterField(
            model_name='actelegislatif',
            name='acteLegislatif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.actelegislatif'),
        ),
    ]
