# Generated by Django 3.1.3 on 2020-11-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201129_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='actelegislatif',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actelegislatif',
            name='uid',
            field=models.TextField(),
        ),
    ]
