# Generated by Django 3.1.3 on 2020-11-29 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201129_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('xsi_type', models.TextField()),
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('legislature', models.TextField()),
                ('cycleDeVie_chrono_dateCreation', models.TextField()),
                ('cycleDeVie_chrono_dateDepot', models.TextField()),
                ('cycleDeVie_chrono_datePublication', models.TextField()),
                ('cycleDeVie_chrono_datePublicationWeb', models.TextField()),
                ('denominationStructurelle', models.TextField()),
                ('provenance', models.TextField()),
                ('titres_titrePrincipal', models.TextField()),
                ('titres_titrePrincipalCourt', models.TextField()),
                ('classification_famille_depot_code', models.TextField()),
                ('classification_famille_depot_libelle', models.TextField()),
                ('classification_famille_classe_code', models.TextField()),
                ('classification_famille_classe_libelle', models.TextField()),
                ('classification_famille_espece_code', models.TextField()),
                ('classification_famille_espece_libelle', models.TextField()),
                ('classification_type_code', models.TextField()),
                ('classification_type_libelle', models.TextField()),
                ('classification_sousType_code', models.TextField()),
                ('classification_sousType_libelle', models.TextField()),
                ('classification_sousType_libelleEdition', models.TextField()),
                ('classification_statutAdoption', models.TextField()),
                ('correction', models.TextField()),
                ('notice_numNotice', models.TextField()),
                ('notice_formule', models.TextField()),
                ('notice_adoptionConforme', models.TextField()),
                ('indexation', models.TextField(null=True)),
                ('imprimerie_ISSN', models.TextField(null=True)),
                ('imprimerie_ISBN', models.TextField(null=True)),
                ('imprimerie_DIAN', models.TextField(null=True)),
                ('imprimerie_nbPage', models.TextField()),
                ('imprimerie_prix', models.TextField(null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dossier')),
            ],
        ),
    ]
