# Generated by Django 3.1.3 on 2020-11-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201129_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='classification_sousType_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='classification_sousType_libelle',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='classification_sousType_libelleEdition',
            field=models.TextField(null=True),
        ),
    ]
