# Generated by Django 3.1.3 on 2020-11-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201129_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='provenance',
            field=models.TextField(null=True),
        ),
    ]
