# Generated by Django 3.1.3 on 2020-11-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201129_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='notice_formule',
            field=models.TextField(null=True),
        ),
    ]
