# Generated by Django 3.1.3 on 2020-11-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201129_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='correction',
            field=models.TextField(null=True),
        ),
    ]
