# Generated by Django 3.1.3 on 2020-11-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201129_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='dossier',
        ),
        migrations.AddField(
            model_name='document',
            name='dossierRef',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
