# Generated by Django 3.1.3 on 2020-11-29 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201129_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('etatCivil_ident_civ', models.TextField()),
                ('etatCivil_ident_prenom', models.TextField()),
                ('etatCivil_ident_nom', models.TextField()),
                ('etatCivil_ident_alpha', models.TextField()),
                ('etatCivil_ident_trigramme', models.TextField(null=True)),
                ('etatCivil_infoNaissance_dateNais', models.TextField()),
                ('etatCivil_infoNaissance_villeNais', models.TextField()),
                ('etatCivil_infoNaissance_depNais', models.TextField()),
                ('etatCivil_infoNaissance_paysNais', models.TextField()),
                ('etatCivil_dateDeces', models.TextField(null=True)),
                ('profession_libelleCourant', models.TextField()),
                ('profession_socProcINSEE_catSocPro', models.TextField()),
                ('profession_socProcINSEE_famSocPro', models.TextField()),
                ('uri_hatvp', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mandat',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('acteurRef', models.TextField()),
                ('legislature', models.TextField(null=True)),
                ('typeOrgane', models.TextField()),
                ('dateDebut', models.TextField()),
                ('datePublication', models.TextField()),
                ('dateFin', models.TextField()),
                ('preseance', models.TextField()),
                ('nominPrincipale', models.TextField()),
                ('infosQualite_codeQualite', models.TextField()),
                ('infosQualite_libQualite', models.TextField()),
                ('infosQualite_libQualiteSex', models.TextField()),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.acteur')),
            ],
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('xsi_type', models.TextField()),
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('typeLibelle', models.TextField()),
                ('poids', models.TextField(null=True)),
                ('adresseDeRattachement', models.TextField(null=True)),
                ('valElec', models.TextField(null=True)),
                ('intitule', models.TextField(null=True)),
                ('numeroRue', models.TextField(null=True)),
                ('nomRue', models.TextField(null=True)),
                ('complementAdresse', models.TextField(null=True)),
                ('codePostal', models.TextField(null=True)),
                ('ville', models.TextField(null=True)),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.acteur')),
            ],
        ),
    ]
