# Generated by Django 3.1.3 on 2020-11-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20201129_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandat',
            name='infosQualite_libQualiteSex',
            field=models.TextField(null=True),
        ),
    ]
