# Generated by Django 3.1.3 on 2020-11-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201129_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organe',
            fields=[
                ('xsi_type', models.TextField()),
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('codeType', models.TextField()),
                ('libelle', models.TextField()),
                ('libelleEdition', models.TextField()),
                ('libelleAbrege', models.TextField()),
                ('libelleAbrev', models.TextField()),
                ('viMoDe_dateDebut', models.TextField()),
                ('viMoDe_dateAgrement', models.TextField(null=True)),
                ('viMoDe_dateFin', models.TextField(null=True)),
                ('organeParent', models.TextField(null=True)),
                ('chambre', models.TextField(null=True)),
                ('regime', models.TextField()),
                ('legislature', models.TextField(null=True)),
                ('secretariat_secretaire01', models.TextField(null=True)),
                ('secretariat_secretaire02', models.TextField(null=True)),
            ],
        ),
    ]
